### ISSUE TITLE
Allow to add search result to result center

### ISSUE THREAD

**Issue by dpayk** [conterra/mapapps-hierarchicalsearch#1]
After performing a search, the user should be able to add the result to the result center. This way, a user could search for several addresses or land parcels and collect all of them in the result center, to export them or start a report.
There should be an additional button in the hierarchical-search window that allows to send the results to the result center. This button should only appear when result center is available and should be hideable via configuration.

**Comment by matthiasstein** [comment]
Added in https://github.com/conterra/mapapps-hierarchicalsearch/releases/tag/1.2.0
