### ISSUE TITLE
Upload does not work correctly

### ISSUE THREAD

**Issue by pleisch** [conterra/mapapps-hierarchicalsearch#4]
After uploading only a "test build" appears in the bundle list (screenshot).
![2019-02-07_08h48_34](https://user-images.githubusercontent.com/47412698/52414721-614fae00-2ae5-11e9-8123-2315ee21099c.png)
[info.txt](https://github.com/conterra/mapapps-hierarchical-search/files/2841011/info.txt)

.

**Comment by matthiasstein** [comment]
I cannot reproduce this behavior in 4.5.0 with release 1.2.2.
