### ISSUE TITLE
'Remove Selected Features From Result Center' is not available

### ISSUE THREAD

**Issue by marcwilkes** [conterra/mapapps-hierarchicalsearch#7]
The option 'Remove Selected Features From Result Center' is not available.

![hierarchical_search](https://user-images.githubusercontent.com/69294548/94447806-80172280-01aa-11eb-9659-16f1e59cf5da.png)

Questions: Could a MemoryStore be used (this option is available, although not recommended, in the QueryBuilder)?

**Comment by matthiasstein** [comment]
This is basically possible but currently not planned.

**Comment by sholtkamp** [comment]
Idea: Test for result-ui

**Comment by sholtkamp** [comment]
Selected elements can be removed from the results when using result-ui.
